- config/locales/en.yml
Minor copy change as per requirements.
https://trello.com/c/fjGHIkAM/49-route-determining-question
> Update copy question 1 teacher route

- .dockerignore
- .github/workflows/build-and-deploy.yml
- Dockerfile
- terraform/config/review.tfvars.json
Build a docker image on PR, merge, update PR, etc
Run snyk scan against image
Push image to ghcr on successful build and scan
ttps://trello.com/c/0i1ePPT2/416-irp-build-docker-image
> Build docker image

- app/models/applicants/personal_detail.rb
https://trello.com/c/w5wmjzI0/65-application-form-gender
As instructed: 
```
Users must enter this question, leaving it blank is not an option. The only 
answers we are allowing are: ‘Male’ and ‘Female’
```
> Update gender options

- docs/adr/0003-introduce-pageobject-via-siteprism.md
This application consists on a high number of sequential questions and answers. The current implementation is making the tests a bit difficult to read and maintain.
We would like to clearly express the steps that the user is taking like:
- The user landed on the gender page
- The user transitioned to the contract detail page
- The user filled in his email address
While we can do that with the current implementation, we would need to rely on modules, shared steps, and many other things that are not really necessary.
> ADR to introduce PageObject via Siteprism for Testing

- app/models/address.rb
- app/models/applicant.rb
- app/models/applicant_progress.rb
- app/models/school.rb
- lib/tasks/auto_annotate_models.rake
- spec/factories/addresses.rb
- spec/factories/applicant_progresses.rb
- spec/factories/applicants.rb
- spec/factories/schools.rb
Annotations were introduced in #30. On this PR I am automating the generation of the annotations in the models, and updating the annotations after all the domain changes.
> Automate annotations on db:migrate

- app/views/pages/start.html.erb
https://trello.com/b/y140nagE/gairp-application-form
Only content changes as per the content designer requirements.
> Update GOV.UK Landing page for IRP

- app/controllers/applicants/employment_details_controller.rb
- app/models/address.rb
- app/models/applicants/employment_detail.rb
- app/models/school.rb
- app/views/applicants/employment_details/new.html.erb
- config/locales/en.yml
- spec/features/teacher_route_completing_the_form_spec.rb
- spec/models/address.rb
- spec/models/address_spec.rb
- spec/models/school_spec.rb
- spec/requests/question_for_employment_details_spec.rb
- spec/support/application_form_steps.rb
https://trello.com/c/GJ9FLJYp/67-application-form-school-name-and-address
Following the work on #62, I am extracting the address as a polymorphic association
with the school. We still need to remove the session dependency from the applicant's
journey which is making testing difficult and more cumbersome.
> Add address to school

- app/views/applicants/employment_details/new.html.erb
- app/views/applicants/submissions/show.html.erb
- app/views/pages/start.html.erb
- spec/features/teacher_route_completing_the_form_spec.rb
- spec/features/trainee_route_completing_the_form_spec.rb
https://trello.com/c/KUvmzg7f/47-govuk-landing-page
https://trello.com/c/GJ9FLJYp/67-application-form-school-name-and-address
Copy changes on Landing page and Employment information.
> Copy changes: landing page, exit page and employment information

- app/views/applicants/submissions/show.html.erb
https://trello.com/c/fsy6rp4P/72-teacher-route-exit-page-copy-application-criteria-is-fulfilled
This is consistent with GOV.UK guidelines.
> Add application complete pannel

- app/models/application_progress.rb
- app/models/kpis.rb
- app/views/system_admin/dashboard/show.html.erb
- db/migrate/20230628135130_add_payment_completed_at_to_applicant_progresses.rb
- db/schema.rb
- spec/factories/application_progresses.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/models/kpis_spec.rb
Create a new widget to show the total number of paid applications
- Add migration for new column payment_completed_at
- Create a new widget to show total paid applications
https://trello.com/c/10D6G2ro
> Create create a widget to show total paid

- app/models/kpis.rb
- app/queries/gender_breakdown_query.rb
- app/views/system_admin/dashboard/show.html.erb
- spec/features/admin_console/dashboard_spec.rb
- spec/queries/gender_breakdown_query_spec.rb
Adds a new widget for the gender breakdown
Creates a new query object to obtain the genders breakdown
Adds a new widget to the dashboard to display the gender breakdown
Adds the necessary tests for the query object and system test for the widget view
https://trello.com/c/0DkrMQTO
> Adds a new widget for the gender breakdown

- app/models/kpis.rb
- app/queries/visa_breakdown_query.rb
- app/views/system_admin/dashboard/show.html.erb
- spec/features/admin_console/dashboard_spec.rb
- spec/queries/visa_breakdown_query_spec.rb
Adds a new widget for the visa breakdown
Creates a new query object to obtain the visa breakdown
Adds a new widget to the dashboard to display the visa breakdown
Adds the necessary tests for the query object and system test for the widget view
https://trello.com/c/8jTbBarw
> Adds a new widget for the visa breakdown

- app/models/kpis.rb
- app/queries/average_age_query.rb
- app/views/system_admin/dashboard/show.html.erb
- spec/features/admin_console/dashboard_spec.rb
- spec/queries/average_age_query_spec.rb
- Create a new query object to calculate the average age
- Add a new widget to the dashboard to display the average age
https://trello.com/c/EgA85Ssr
> Add a new widget for the average age

- app/models/kpis.rb
- app/views/system_admin/dashboard/show.html.erb
- db/migrate/20230628110938_add_rejection_completed_at_to_applicant_progresses.rb
- db/schema.rb
- spec/factories/applicant_progresses.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/models/kpis_spec.rb
Create a new widget to show the total number of rejctions
- Creates a new migration to add a new column to the application_progresses table
- Creates a new KPI widget to count the total number of rejections
https://trello.com/c/iv6YAVBl
> Create create a widget to show total rejections

- app/controllers/applicants/salaried_course_details_controller.rb
- app/views/pages/ineligible.html.erb
- app/views/pages/ineligible_salaried_course.html.erb
- app/views/pages/shared/_body.html.erb
- app/views/pages/shared/_footer.html.erb
- config/routes.rb
- spec/features/trainee_route_completing_the_form_spec.rb
- spec/support/application_form_steps.rb
https://trello.com/c/dlHn4AWE/81-trainee-teacher-exit-page-copy-for-are-you-currently-employed-question
Update the copy for the Trainee question: Are you currently employed?. So far, this is the only question with a different copy for the ineligible path.
> Trainees: Different content for salaried question if not eligible

- Gemfile
- db/seeds.rb
We need the faker gem out too since it is used by the factories
https://trello.com/c/
> Move faker gem out of development group

- Gemfile
- Gemfile.lock
- app/controllers/system_admin/applicants_controller.rb
- app/views/system_admin/applicants/index.html.erb
Add pagination for the list of applicants
https://trello.com/c/9V9eXyNR
> Add pagination for the list of applicants

- app/controllers/admin_controller.rb
- app/controllers/system_admin/applicants_controller.rb
- app/controllers/system_admin/dashboard_controller.rb
- app/views/layouts/admin.html.erb
- app/views/system_admin/applicants/show.html.erb
Makes a new layout for the system-admin controllers that include a little
navigation menu and fixes the outdated application show view
> Update Admin Layout and Fix application show

- app/models/kpis.rb
- app/views/system_admin/dashboard/show.html.erb
- spec/features/admin_console/dashboard_spec.rb
Small fixes for the kpi widgets from the QA feedback
> Small fixes from qa feedback

- app/models/applicants/subject.rb
- app/views/pages/start.html.erb
- config/locales/en.yml
https://trello.com/c/IaH6ZW93/139-edits-to-personal-information-page-reviewed-by-laura
https://trello.com/c/Gh2fuUax/138-edit-to-subject-page-reviewed-by-laura
https://trello.com/c/1ecJc15F/137-landing-page-copy-reviewed-by-laura-2nd-review
Address feedback from the Content Designer
**
**
> Address content designer feedback

- app/models/kpis.rb
- app/queries/time_to_home_office_checks_query.rb
- app/views/system_admin/dashboard/show.html.erb
- spec/features/admin_console/dashboard_spec.rb
- spec/queries/time_to_home_office_checks_query_spec.rb
Create a new KPI Widget to show the average time to complete Home Office checks
https://trello.com/c/8pqea6hU
https://trello.com/c/AyFhAzBq
> KPI Widget: HO Checks

- app/models/kpis.rb
- app/queries/time_to_banking_approval_query.rb
- app/views/system_admin/dashboard/show.html.erb
- db/migrate/20230705163541_add_payment_completed_at_to_application_progresses.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/applications.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/queries/time_to_banking_approval_query_spec.rb
Create a new KPI Widget to show the average time to complete Banking Approval
https://trello.com/c/l4p85qn2
https://trello.com/c/U9rnZY63
> KPI Widget: Banking Approval

- db/migrate/20230705163541_add_payment_completed_at_to_application_progresses.rb
- db/schema.rb
Remove the db migration to create the payment column that wasn't needed
> Remove the migration that was not needed

- app/controllers/system_admin/applicants_controller.rb
- app/views/system_admin/applicants/index.html.erb
- app/views/system_admin/applicants/show.html.erb
- spec/features/admin_console/applications_list_spec.rb
Add the required columns to the applications list and fix the application view
https://trello.com/c/GBExwYdk
https://trello.com/c/R1orWERl
https://trello.com/c/x1dzCSOS
https://trello.com/c/lqC7Hdaw
https://trello.com/c/D8rmPY62
https://trello.com/c/38F3tYnq
https://trello.com/c/JJAosvjH
https://trello.com/c/NSVFzesM
> Application List Columns

- app/views/applicants/submissions/show.html.erb
- app/views/pages/start.html.erb
- config/locales/en.yml
https://trello.com/c/1ecJc15F/137-landing-page-copy-reviewed-by-laura-2nd-review
https://trello.com/c/655rPqvz/136-email-notification-copy-reviewed-by-laura
https://trello.com/c/VRKf2Xsl/135-exit-submission-page-copy-reviewed-by-laura
https://trello.com/c/IaH6ZW93/139-edits-to-personal-information-page-reviewed-by-laura
Includes the second set of content changes provided by the content designer.
> Content updates (2nd review)

- app/helpers/application_helper.rb
- app/javascript/packs/stylesheets/custom.scss
- app/models/application_progress.rb
- app/models/kpis.rb
- app/queries/time_to_banking_approval_query.rb
- app/queries/time_to_home_office_checks_query.rb
- app/queries/time_to_initial_checks_query.rb
- app/queries/time_to_payment_confirmation_query.rb
- app/views/layouts/admin.html.erb
- app/views/system_admin/applicants/index.html.erb
- app/views/system_admin/dashboard/show.html.erb
- db/migrate/20230706125551_add_banking_approval_completed_at_to_application_progresses.rb
- db/migrate/20230706134855_rename_payment_completed_at_to_payment_confirmation_completed_at.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/application_progresses.rb
- spec/factories/applications.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/models/kpis_spec.rb
- spec/queries/time_to_banking_approval_query_spec.rb
- spec/queries/time_to_home_office_checks_query_spec.rb
- spec/queries/time_to_initial_checks_query_spec.rb
- spec/queries/time_to_payment_confirmation_query_spec.rb
- spec/queries/time_to_school_checks_query_spec.rb
This addresses multiple changes from TOR's feeback meeting:
- Adds a new extra column on the list of applicants for payment confirmation
- Updates the titles and subtitles of various KPI Widgets
- Adds a new widget to keep track of the Average Time for Payment Confirmation
- Updates the seeds to create payment confirmation applications
- Renames the column payment_completed_at to payment_confirmation_completed_at for consistency
- Removes the menu links at top for CSV download to avoid confusion
- Refactors the ugly use of html_attributes on the table with a CSS class
> Adjustments from TOR's Feedback

- app/javascript/packs/stylesheets/custom.scss
- app/queries/time_to_payment_confirmation_query.rb
- spec/factories/application_progresses.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/queries/time_to_payment_confirmation_query_spec.rb
Fix the time to payment widget error where the dates were reversed
> Fix time to Payment Widget

- app/controllers/system_admin/applicants_controller.rb
- app/models/application_progress.rb
- app/views/system_admin/applicants/edit.html.erb
- app/views/system_admin/applicants/show.html.erb
- db/migrate/20230706153246_add_rejection_reason_to_application_progress.rb
- db/schema.rb
- spec/factories/application_progresses.rb
Update copy for the Appllcation view
- Update copy for the the application view and update progress form
- Use the official components for the application progress view
- Introduce the new rejection reason column
https://trello.com/c/Ob9mKDfe
> Application View Copy Changes

- app/javascript/packs/stylesheets/custom.scss
- app/models/school.rb
- app/views/system_admin/applicants/index.html.erb
- app/views/system_admin/applicants/show.html.erb
- app/views/system_admin/dashboard/show.html.erb
- config/initializers/date_formats.rb
- db/migrate/20230707122123_remove_postcode_from_schools.rb
- db/schema.rb
- spec/factories/applicants.rb
- spec/factories/applications.rb
- spec/factories/schools.rb
- spec/features/admin_console/applications_list_spec.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/models/school_spec.rb
- Change KPI Widget titles and positioning
- Display Applicant and School address on the admin console
- Remove postcode from school model
- Add date format for admin console
- Fix seeds and factories to generate addresses for schools and applicants
> Address feedback for the backend

- app/controllers/system_admin/applicants_controller.rb
Scope the list of applicants to the ones that has been fully submitted
> Hotfix List of Applicants

- app/controllers/system_admin/reports_controller.rb
- app/models/reports/standing_data.rb
- app/views/system_admin/reports/index.html.erb
- spec/features/admin_console/reports_spec.rb
- spec/models/reports/standing_data_spec.rb
https://trello.com/c/6COFDjZx/127-service-settings-download-csv-for-standing-data
Following work on #144, we are including a new report: `Standing Data Report`, which 
returns the following fields:
```ruby
"urn",
"given_name",
"family_name",
"phone_number",
"email_address",
"address_line_1",
"postcode",
```
With the following conditions:
1. School checks are completed
2. Banking details are not approved yet
> Export CSV: Standing Data

- app/models/applicants/subject.rb
- app/views/applicants/personal_details/new.html.erb
- app/views/applicants/salaried_course_details/new.html.erb
- app/views/pages/shared/_footer.html.erb
- app/views/pages/start.html.erb
- config/locales/en.yml
- spec/features/admin_console/dashboard_spec.rb
https://trello.com/c/SXoLMSXn/150-address-copy-changes-from-laura
Addresses content changes by Laura: content designer.
> Update copy changes

- terraform/aks/databases.tf
Enable CITEXT extention for Postgresql
> Enable CITEXT extention for Postgresql

- app/controllers/admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/system_admin/settings_controller.rb
- app/models/app_settings.rb
- app/models/gatekeeper.rb
- app/models/setting.rb
- app/views/layouts/admin.html.erb
- app/views/pages/closed.html.erb
- app/views/system_admin/settings/edit.html.erb
- config/routes.rb
- db/migrate/20230713071036_create_settings.rb
- db/migrate/20230713082454_rename_settings_to_app_settings.rb
- db/migrate/20230721082851_enable_opening_times.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/settings.rb
- spec/features/admin_console/settings_spec.rb
- spec/features/open_close_spec.rb
- spec/models/app_settings_spec.rb
- spec/models/gatekeeper_spec.rb
- spec/models/setting_spec.rb
- spec/rails_helper.rb
- spec/support/application_form_assertions.rb
https://trello.com/c/aEqooIHr/129-service-settings-add-a-toggle-to-open-close-applications-service
https://trello.com/c/KBaRff09/89-application-window-closed-page
Enables/disables the service based on two attributes that are configured via the Settings page on the
admin page.
> Window open close dates

- app/models/reports/home_office.rb
- spec/models/reports/home_office_spec.rb
https://trello.com/c/ZHLorhH6/126-service-settings-download-csv-for-ho
Joins `given_name` and `family_name` in the column `full_name`.
> Use full_name in report for Home Office

- config/locales/en.yml
https://trello.com/c/SXoLMSXn/150-address-copy-changes-from-laura
> Update copy for entering the address

- app/models/reports/payroll.rb
- spec/models/reports/payroll_spec.rb
https://trello.com/c/NMAhMvxu/128-service-settings-download-csv-for-payroll
As per requirements, we must generate the same fields as the default CSV for Payroll is expecting.
> Update fields in Payroll CSV export file

- app/views/applicants/personal_details/new.html.erb
- config/locales/en.yml
https://trello.com/c/SXoLMSXn/150-address-copy-changes-from-laura
Updates copy for the Personal Details form when requesting the applicant address.
> Update enter address copy

- app/models/reports/payroll.rb
- db/schema.rb
- spec/models/reports/payroll_spec.rb
https://trello.com/c/NMAhMvxu/128-service-settings-download-csv-for-payroll
Adds defaults to the CSV export as per new requirements.
> Add default values to CSV for payroll

- app/models/applicants/personal_detail.rb
- spec/models/applicants/personal_detail_spec.rb
-------
Set the minimum age for `PersonalDetail.date_of_birth` to 22 years old
[Ticket](https://trello.com/c/tqgE7wP3/83-s-personal-info-validation-minimum-age-of-18)
> Add minimum age validation on `PersonalDetail.date_of_birth`

- app/views/pages/closed.html.erb
-------
* Jane to June
* Update contact section
[89-application-window-closed-page](https://trello.com/c/KBaRff09/89-application-window-closed-page)
> Closed page copy changes

- app/views/pages/start.html.erb
-------
Add missing link on landing page
[landing-page-copy-reviewed-by-laura-2nd-review](https://trello.com/c/1ecJc15F/137-landing-page-copy-reviewed-by-laura-2nd-review)
> Fix missing link

- app/models/reports/payroll.rb
- spec/models/reports/payroll_spec.rb
* tax_basis set to 0
* ni_category set to ''
* addr_line_2 set to city or town
* addr_line_6 set to postcode
[service-settings-download-csv-for-payroll](https://trello.com/c/NMAhMvxu/128-service-settings-download-csv-for-payroll)
> Fix Payroll CSV file

- app/controllers/applicants/personal_details_controller.rb
- app/models/applicant.rb
- app/models/applicants/personal_detail.rb
- app/models/reports/home_office.rb
- app/views/applicants/personal_details/new.html.erb
- app/views/system_admin/applicants/show.html.erb
- config/locales/en.yml
- db/migrate/20230814222343_add_middle_name_to_applicant.rb
- db/schema.rb
- spec/factories/applicants.rb
- spec/features/admin_console/applications_list_spec.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/features/teacher_route_completing_the_form_spec.rb
- spec/queries/average_age_query_spec.rb
- spec/spec_helper.rb
Add middle name for applicant
- Add migration to include middle name column in applicants table
- Add middle name field to form and controllers
- Update tests
- Include middle name in Home Office CSV download
https://trello.com/c/0DIt7nKO
> Add middle name for applicant

- spec/features/admin_console/dashboard_spec.rb
- spec/queries/average_age_query_spec.rb
> Fix average age specs

- app/helpers/application_helper.rb
- app/views/pages/closed.html.erb
-------
Copy update on the closed page
[closed-page](https://trello.com/c/debvYG4e/160-s-new-copy-for-closed-page)
> Copy update closed page

- app/helpers/application_helper.rb
- app/views/pages/closed.html.erb
- spec/features/admin_console/settings_spec.rb
- spec/features/open_close_spec.rb
copy change closed page
https://trello.com/c/jBjek89l/172-screenshot-2023-08-16-at-085712png
> Copy changes on the closed page

- app/views/pages/start.html.erb
-------
Update start page copy
> Update start page copy

- public/robots.txt
Reverts DFE-Digital/get-a-teacher-relocation-payment#174
> Revert "Delete robots.txt"

- Gemfile
- Gemfile.lock
- app/controllers/applicants/personal_details_controller.rb
- app/views/applicants/personal_details/new.html.erb
- config/initializers/invisible_captcha.rb
- db/schema.rb
Add invisible captcha gem
- Tracks very fast submission of the personal details form
- Adds a honeypot for a "username" field at the personal details form
https://trello.com/c/5SBv71KC
> Add invisible captcha gem

- app/controllers/system_admin/applicants_controller.rb
- app/models/duplicate_application.rb
- spec/features/admin_console/duplicates_search_spec.rb
Show the duplicates only once on the list of duplicates table,
even when they have multiple matches, like same email AND passport.
https://trello.com/c/i2516UXM
> Unique Duplicates

- README.md
-------
Update README.md with Contingency section
based on chat with Duncan
[contingency](https://trello.com/c/6m4Ugvl4/167-team-to-speak-to-duncan-about-contingency-plan-if-the-application-form-goes-down)
> Update README.md with Contingency section

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
-------
Private Beta banner with feedback link
[175](https://trello.com/c/cgDx9fV1/175-sbuild-feedback-form-behind-the-private-beta)
[166](https://trello.com/c/dNw6BOUv/166-s-update-banner-from-alpha-to-private-beta)
> Add Beta banner with feedback form

- app/views/pages/privacy.html.erb
- config/routes.rb
-------
* add privacy page
* update routes with the new privacy page
https://trello.com/c/WRHhlGUO/165-s-display-privacy-policy-on-application-form
> Add privacy page

- app/views/layouts/application.html.erb
-------
Add privacy link in application footer
https://trello.com/c/WRHhlGUO/165-s-display-privacy-policy-on-application-form
> Add privacy link in application layout footer

- app/views/layouts/admin.html.erb
- app/views/shared/_notices.html.erb
- app/views/system_admin/applicants/duplicates.html.erb
- app/views/system_admin/applicants/index.html.erb
- app/views/system_admin/dashboard/show.html.erb
- app/views/system_admin/reports/index.html.erb
- app/views/system_admin/settings/edit.html.erb
- app/views/system_admin/users/index.html.erb
- config/locales/en.yml
- spec/features/admin_console/applications_list_spec.rb
- spec/features/admin_console/dashboard_spec.rb
- spec/features/admin_console/duplicates_search_spec.rb
- spec/features/admin_console/settings_spec.rb
- spec/features/admin_console/users_spec.rb
- spec/features/open_close_spec.rb
Various copy and styles changes on the admin section
https://trello.com/c/kpaToTjR/179-copy-admin-portal-changes
> Admin copy changes

- app/models/summary.rb
- app/steps/base_step.rb
- app/views/layouts/application.html.erb
- app/views/pages/index.html.erb
- app/views/submission/summary.html.erb
- config/locales/steps.en.yml
- spec/models/summary_spec.rb
- spec/steps/application_route_step_spec.rb
- spec/steps/school_details_step_spec.rb
- spec/steps/subject_step_spec.rb
Copy changes on:
* home page 
* summary page
* some step pages
https://trello.com/c/uLjJpduS/161-copy-application-windows-to-be-added-to-landing-page
> Copy changes

- app/views/pages/sitemap.xml.erb
- config/initializers/sitemap.rb
- config/routes.rb
-------
Add a basic sitemap.xml
https://trello.com/c/pLppvoW2/173-s-submit-application-site-map-and-add-a-link-to-irp-application-on-policy-page
> Basic sitemap

- app/controllers/pages_controller.rb
- config/routes.rb
> Test sentry config

- app/views/pages/index.html.erb
-------
Remove deadline section from homepage
https://trello.com/c/vLVH34iJ/186-deadline-text-on-front-page-removal
> Remove deadline section from homepage

- app/views/system_admin/applicants/show.html.erb
Add contract start date to the application view
https://trello.com/c/1G24ySWc
> add contract start date to application view

- terraform/aks/application.tf
- terraform/aks/databases.tf
- terraform/aks/variables.tf
Add redis and worker app
redis
- single redis instance per environment 
- sets REDIS_URL
worker
- single worker app per environment, 
- set to 0 replicas in this PR so doesn't run anything.
- unset replicas and add command when ready
https://trello.com/c/mMxjn7UI/621-trp-add-redis-and-worker-app
> Add redis and worker app

- .github/workflows/database-backup.yml
Add a daily database backup workflow.
This runs a pg_dump, which is then uploaded to an Azure storage account.
https://trello.com/c/aswCkooZ/644-irp-add-daily-backup-workflow
> Add database backup workflow

- app/controllers/application_controller.rb
- app/controllers/system_admin/applicants_controller.rb
- app/models/application.rb
- app/models/kpis.rb
- app/queries/average_age_query.rb
- app/queries/gender_breakdown_query.rb
- app/queries/nationality_breakdown_query.rb
- app/queries/rejection_reason_breakdown_query.rb
- app/queries/route_breakdown_query.rb
- app/queries/subject_breakdown_query.rb
- app/queries/visa_breakdown_query.rb
- app/services/submit_form.rb
- spec/factories/applications.rb
- spec/features/admin_console/applications_list_spec.rb
- spec/features/admin_console/download_qa_csv_file_spec.rb
- spec/features/admin_console/duplicates_search_spec.rb
- spec/models/application_spec.rb
- spec/models/kpis_spec.rb
- spec/queries/average_age_query_spec.rb
- spec/queries/gender_breakdown_query_spec.rb
- spec/queries/nationality_breakdown_query_spec.rb
- spec/queries/rejection_reason_breakdown_query_spec.rb
- spec/queries/route_breakdown_query_spec.rb
- spec/queries/subject_breakdown_query_spec.rb
- spec/queries/visa_breakdown_query_spec.rb
Remove concept of submitted application
The SubmitForm service creates submitted application and we no longer
have unsubmitted applications to consider in the system-admin code.
The Forms are now what used to be unsubmitted applications.
https://trello.com/c/hr5LvhT7/205-code-cleanup
> Code cleanup

- app/views/pages/closed.html.erb
closed page
https://trello.com/c/debvYG4e/160-s-copy-new-copy-for-closed-page
> Copy change

- app/controllers/application_controller.rb
- app/controllers/system_admin/applicants_controller.rb
- app/models/application.rb
- app/models/kpis.rb
- app/queries/average_age_query.rb
- app/queries/gender_breakdown_query.rb
- app/queries/nationality_breakdown_query.rb
- app/queries/rejection_reason_breakdown_query.rb
- app/queries/route_breakdown_query.rb
- app/queries/subject_breakdown_query.rb
- app/queries/visa_breakdown_query.rb
- app/services/submit_form.rb
- spec/factories/applications.rb
- spec/features/admin_console/applications_list_spec.rb
- spec/features/admin_console/download_qa_csv_file_spec.rb
- spec/features/admin_console/duplicates_search_spec.rb
- spec/models/application_spec.rb
- spec/models/kpis_spec.rb
- spec/queries/average_age_query_spec.rb
- spec/queries/gender_breakdown_query_spec.rb
- spec/queries/nationality_breakdown_query_spec.rb
- spec/queries/rejection_reason_breakdown_query_spec.rb
- spec/queries/route_breakdown_query_spec.rb
- spec/queries/subject_breakdown_query_spec.rb
- spec/queries/visa_breakdown_query_spec.rb
Reverts DFE-Digital/get-a-teacher-relocation-payment#259
> Revert "Code cleanup"

- app/models/reports/home_office.rb
- spec/models/reports/home_office_spec.rb
https://trello.com/c/etFQUL8H/202-ho-csv
> Add NIN column to HO report

- app/controllers/system_admin/applicants_controller.rb
Set on the session all the ids from the results as opposed to only the ones from the first page.
https://trello.com/c/N2X2y9Uv
> QA Download all pages

- app/views/system_admin/applicants/duplicates.html.erb
Add pagination and show the IP address for the list of applicants
https://trello.com/c/pJwg64Po
> Pagination and IP Address to Duplicates

- app/javascript/packs/stylesheets/custom.scss
White text color
https://trello.com/c/hPT1pL2Y/209-add-new-kpi-widget-with-a-breakdown-of-the-each-status
> KPI statuses styling

- app/models/duplicate_application.rb
- app/views/system_admin/applicants/duplicates.html.erb
- Search by ip address
https://trello.com/c/647fM8td
> Search duplicates by IP Address

- app/services/report.rb
So that the report returns the data
> Cache csv data in report service

- app/models/reports/applications.rb
- spec/models/reports/applications_spec.rb
* Change report all application columns order
* Add rejection reason column
https://trello.com/c/T0Auju6T/207-add-a-new-option-to-reports-section-to-download-all-applicants-on-the-submitted-state
> Change report all application columns order

- app/controllers/system_admin/applicants_controller.rb
- app/models/application_progress.rb
- app/models/reports/qa_report.rb
- app/views/system_admin/applicants/edit.html.erb
- app/views/system_admin/applicants/show.html.erb
- db/migrate/20231002115920_rename_rejection_details_to_comments.rb
- db/schema.rb
- spec/factories/application_progresses.rb
- spec/features/admin_console/update_progress_spec.rb
- spec/models/application_progress_spec.rb
- spec/models/reports/qa_report_spec.rb
Rename the column rejection details from application progress into comments
https://trello.com/c/kAp2EjAn
> Rename Rejection Details column to Comments

- .rubocop.yml
- app/controllers/pages_controller.rb
- app/controllers/system_admin/dashboard_controller.rb
- app/models/event.rb
- app/models/kpis.rb
- app/queries/forms_funnel_query.rb
- app/services/step_flow.rb
- app/services/submit_form.rb
- app/services/update_form.rb
- app/views/system_admin/dashboard/show.html.erb
- config/application.rb
- config/brakeman.ignore
- config/events/filtered_attributes.yml
- db/migrate/20230928111338_create_events.rb
- db/schema.rb
- spec/factories/events.rb
- spec/factories/urns.rb
- spec/fixtures/urns.yml
- spec/models/event_spec.rb
- spec/models/kpis_spec.rb
- spec/queries/forms_funnel_query_spec.rb
- spec/requests/step_spec.rb
- spec/services/step_flow_spec.rb
- spec/services/submit_form_spec.rb
- spec/services/update_form_spec.rb
Provides two widgets that display form funnel by eligibility
[Card](https://trello.com/c/dIg4iOGA/213-analytics-to-track-when-applicants-become-ineligible)
> Basic Form analytics

- app/models/application_progress.rb
new reason `unable to complete school checks` added
https://trello.com/c/mqNg7NcZ/221-add-another-reason-for-rejection
> Add rejection reason

- app/validators/application_progress_validator.rb
- spec/validators/application_progress_validator_spec.rb
-------
More date validation on application progress
https://trello.com/c/yfRLy1lJ/225-add-validation-to-the-year-for-the-update-progress-page
> Add date validation on application progress

- Dockerfile
- config/application.rb
- config/initializers/assets.rb
- db/migrate/20230630083744_add_default_values_to_boolean_fields.rb
- db/migrate/20231009110217_add_application_indexes.rb
> Fix assets

- Gemfile
- Gemfile.lock
- app/models/urn.rb
To avoid concurrency issue with urn next method
> Use concurrent Array and Hash

- config/initializers/nationalities.rb
Add nationality Lesotho
https://trello.com/b/y140nagE/gairp-application-form
> Add nationality Lesotho

- README.md
- docs/azure-login.md
Adding documentation about the login functionality with Azure
https://trello.com/c/htGyKRyL
> Documenting the login functionality

- app/views/pages/closed.html.erb
Update closed page copy
https://trello.com/c/uisC033E/234-add-new-closed-page-copy
> Update closed page

- app/views/layouts/admin.html.erb
> Fix flipper menu url

- Makefile
- terraform/custom_domains/infrastructure/config/trp.tfvars.json
Fix product tag
Required for correct billing
https://trello.com/c/uYzoqzjx/430-irp-outstanding-deployment-tasks
> Update product tag

- docs/form_funnel.md
- docs/report-template.md
* Report Template
* Form analytics
> Extra documentation

- app/views/pages/index.html.erb
Update the landing page with the latest content for the next application window.
https://trello.com/c/7HIMxjYX/267-implement-new-landing-page-content
> Update landing page

- app/views/govuk_notify_mailer/application_submission.text.erb
- app/views/submission/show.html.erb
Update the dates on the submission page and email content.
https://trello.com/c/T0ADq795/269-submission-page-and-submission-notify-email-content-amended
> Update email and submission page

- app/views/pages/index.html.erb
Reword the expression of interest content and link.
https://trello.com/c/7HIMxjYX/267-implement-new-landing-page-content
> Update expression of interest

- .github/actions/deploy/action.yml
- .github/actions/smoke-test/action.yml
- bin/smoke
Add smoke test to the build-and-deploy workflow post deployment
https://trello.com/c/uYzoqzjx/430-irp-outstanding-deployment-tasks
Check review app deploys and runs smoke test
run smoke test for any env e.g.
bin/smoke https://teacher-relocation-payment-pr-342.test.teacherservices.cloud current-sha
> Add smoke test post deployment

- app/views/govuk_notify_mailer/application_submission.text.erb
- app/views/pages/index.html.erb
- app/views/submission/show.html.erb
https://dfedigital.atlassian.net/browse/CAPT-1607
> Content updates for April 2024 claim window

- app/views/layouts/application.html.erb
Updates the footer to add links and remove the help and T&C elements.
> Updates page footer

- terraform/aks/application.tf
- terraform/aks/config/qa.tfvars.json
- terraform/aks/config/review.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio.
Service Onboard to Logit.io for non prod.
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio.
Logs : https://kibana-uk1.logit.io/s/b2876053-0173-44fc-983d-99567292ba31/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'8ac115c0-aac1-11e8-88ea-0383c11b333a',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_q=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8ac115c0-aac1-11e8-88ea-0383c11b333a',key:kubernetes.deployment.name,negate:!f,params:(query:teacher-relocation-payment-pr-424),type:phrase),query:(match_phrase:(kubernetes.deployment.name:teacher-relocation-payment-pr-424)))),query:(language: …
> Service Onboard to Logit.io

- terraform/aks/application.tf
- terraform/aks/config/qa.tfvars.json
- terraform/aks/config/review.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
Reverting logitio  hanges , which is not required for this service ,  it is going to retire soon.
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio
> logitio changes reverted

- .github/workflows/database-backup.yml
Updated actions to use shared kubectl action
https://trello.com/c/
> Updated pipeline to use shared action

- app/models/reports/applications.rb
- spec/models/reports/applications_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2079
- Add school details to applications CSV report
> Add school details to applications CSV report
