.env.example
.gitignore
app/controllers/system_admin/applicants_controller.rb

Since the app will deployed to Heroku and it will be publicly available, we should add, at a bare minimum, some form of basic Authentication.
This adds basic HTTP authentication to the whole app ( since at the moment doesn't matter if you access the backend or frontend, it should all be behind authentication )
https://trello.com/c/xEwS0GDo

add basic http auth for system admin (temporary)

---

Gemfile

We are getting this error:
```bash
[!] There was an error parsing `Gemfile`: 'shoulda-matchers,~> 5.0' is not a valid gem name because it contains whitespace. Bundler cannot continue.
>    gem "shoulda-matchers," "~> 5.0"
```
For some reason, this was not picked by our CI. I probably merged it too quickly.
After merging, the `bundle install` works correctly

Fix typo on Gemfile

---

spec/features/teacher_route_completing_the_form_spec.rb
spec/features/trainee_route_completing_the_form_spec.rb
spec/rails_helper.rb
spec/support/application_form_steps.rb

[Trello card](https://trello.com/c/e8nGGnsH/18-add-system-test-for-the-trainee-route)
Extends system tests for the Trainee route. The current state only covers the Teacher route, 
and although it is good enough for an MVP, it won't allow us to properly evolve it.
I have taken the following actions:
1. Rename the existing system test to clarify the journey that it is covering
2. Add a new system test for the Trainee route (`trainee_route_completing_the_form_spec.rb`)
3. Extract common steps for both tests into a common file
from:
```bash
spec/features/
└── completing_the_form_spec.rb
0 directories, 1 file
```
to:
``` bash
spec/features/
├── teacher_route_completing_the_form_spec.rb
└── trainee_route_completing_the_form_spec.rb
0 directories, 2 files
```
1. On the current steps we are not …

Extend system tests for trainee route

---

.rubocop.yml
Gemfile
db/migrate/20230602121235_remove_columns_from_applicants.rb

Make our Lint happier by:
1. Ignoring rule BulkChangeTable via Rubocop
2. Remove duplicated gem definition
As a side goal [we are making a migration reversible](c9efd8a35bdc04b386fc5f7d0e5b1bfe6e5570ca).

Add lint fixes for CI

---

.rubocop.yml
app/models/applicants/personal_detail.rb
app/validators/email_format_validator.rb
config/locales/en.yml
spec/validators/email_format_validator_spec.rb

**Context**
The email address field on the personal details page was only validated for presence. We now want to ensure that the format the email entered 'looks like' a real email.
**Changes**
- Add new custom  validator class `EmailFormatValidator` which uses rules set out in https://github.com/alphagov/notifications-utils/blob/fd3ba3db8cfaf4ad5308aaf5efdcd4e0cf3730e8/notifications_utils/recipients.py
- See code comment for more information
- Use this new formatter in the `Applicants::PersonalDetail` model.
- Add error message to translations file
**Guidance for review**
- Enter an incorrect email and check that it errors
Some examples:
Invalid:
Valid:
Error summary:

Add email address format validator

---

.github/workflows/ci.yml

Update the setup-ruby version to use the v1 on the Lint action just the same
as is done on the Rspec action.
So we can avoid dependabot making new pullrequest for each minor version

update setup ruby to use v1

---

app/views/applicants/salaried_course_details/new.html.erb

https://trello.com/c/glMpGVP0/55-trainee-route-place-on-salaried-course
It uses a `hint` attribute on the question to assess the current employment status
for trainees instead of using HTML markup.
**From**
**To**

Use GOV.UK convention for hint on 

---

app/models/applicants/personal_detail.rb
spec/models/applicants/personal_detail_spec.rb
spec/validators/day_month_year_date_validator_spec.rb

Depends on #33 to fix issues with `nil` years or dates that are partially empty
https://trello.com/c/gIQaRF2K/62-application-form-date-of-birth
Adds day, month, year validation for the `birth day` of the applicant.  The validation will 
make sure that all the fields are present and that the date is valid.
1. I have reused the `DayMonthYearDateValidator` introduced in #31
2. I have introduced [duplication on the validation](https://github.com/DFE-Digital/international-teacher-relocation-payment/commit/cbb6246d556015f958ed2be81029324ac6ba129d); I have not 
extracted out the duplicated code as I would like to have a simple PR so this story 
can be properly tested. But I will proceed next with the refactoring.
1. Remove duplication between `start_date_contract` and `entry_date`
2. Unify …

Show validation error on the date_of_birth attribute

---

app/controllers/applicants/entry_dates_controller.rb
app/models/applicants/entry_date.rb
spec/models/applicants/entry_date_spec.rb

https://trello.com/c/TVJxCZSc/54-teacher-route-date-of-entry
Adds validation for the `EntryDate` of the users. The validation will 
make sure that all the fields are present and that the date is valid.
1. I have reused the `DayMonthYearDateValidator` introduced in #31
2. I have introduced [duplication on the validation](https://github.com/DFE-Digital/international-teacher-relocation-payment/commit/cbb6246d556015f958ed2be81029324ac6ba129d); I have not 
extracted out the duplicated code as I would like to have a simple PR so this story 
can be properly tested. But I will proceed next with the refactoring.
3. I have introduced a [fix that prevents `nil` years making a date valid](79f6b23b31c1d085fcfdd02b97166174d7ebe46f). This fix has automatically propagated to the `start contract question` …

Add pending validations for Entry Date question.

---

Gemfile
Gemfile.lock

Sassc dependency was inadvertently introduced in #30 as a side effect of adding the 
gem `better_errors`. This library is deprecated although it is under maintenance. They 
recommend users to move to Dart Sass.
On this PR I am removing this dependency so we can run the application with the following error:
```
iCalling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/Users/pmanrubia/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in …
```

Remove dependency from sassc

---

app/models/applicants/personal_detail.rb
spec/models/applicants/personal_detail_spec.rb

https://trello.com/c/gIQaRF2K/62-application-form-date-of-birth
Add two new validations to the date of birth of an applicant:
1. The date of birth **must** not be in the future
2. Applicants **must** be below 80 years old.

Add extra validations to date of birth

---

app/models/applicants/personal_detail.rb
spec/models/applicants/employment_detail_spec.rb
spec/models/applicants/personal_detail_spec.rb
spec/support/postcode_validation.rb

The postcode validator was introduced in #3 and it was only applied to 
the school address. On #41 we introduced the address for the applicant, 
hence we need to apply the same validation.
Postcode validation is used for applicants and schools, so it makes sense to
check that it is enabled on both models.
I am extracting a Shared Examples file for the postcode so it can be reused also
on the school:
```ruby
include_examples "a valid UK postcode", described_class
```
For `Applicants::PersonalDetail`
```bash
validations
...
is expected to validate that :city cannot be empty/falsy
is expected not to validate that :county cannot be empty/falsy
is expected to validate that :postcode cannot be empty/falsy
is expected to validate that :sex is either ‹"female"›, ‹"male"›, or ‹"other"›
***accepts …
```

Include postcode validations

---

Gemfile
Gemfile.lock
app/models/applicants/personal_detail.rb
app/views/applicants/personal_details/new.html.erb
config/initializers/phone_number.rb
config/locales/en.yml
spec/models/applicants/personal_detail_spec.rb
spec/support/phone_number_validations.rb

https://trello.com/c/PV6vpXTU/61-application-form-phone-number
The [design system for GOV.UK for phone numbers](https://design-system.service.gov.uk/patterns/telephone-numbers/) is still not conclusive when it 
comes to mobile numbers, but it has some experimental guidelines that I have
followed on this PR.
For the validations, at the time of writing this commit, the design system suggests 
[using a Library from Google named libphonenumber](https://github.com/google/libphonenumber). There is no implementation for
Ruby, but they point you towards one of the following:
1. [GitHub - ianks/mini_phone](https://github.com/ianks/mini_phone): A fast phone number parser, validator and formatter 
for Ruby. This gem binds to Google’s C++ libphonenumber for spec-compliance 
and performance.
3. …

Validate phone number with international codes

---

db/migrate/20230612153024_create_schools.rb

It seems that this was lost in a merge/rebase and we can't run a 
clean db:migrate from a blank database. This is not critical, because 
we usually load the database with rails db:setup, but it is worth 
having it back.

Restore foreign key in migration for schools

---

app/models/applicants/subject.rb

As instructed, we are removing the option `general science` from the subject questions.
https://trello.com/c/KBsBnpwk/56-trainee-route-training-subject

Update subjects: remove general science

---

app/models/urn.rb
spec/models/urn_spec.rb

https://trello.com/c/acwINfog/32-m-generate-urn-for-applications-on-submission
`Urn` represents a Uniform Resource Name (URN) generator. It generates a URN 
with a fixed prefix and a random alphanumeric suffix.
Uses [DEC alphabet](https://gunkies.org/wiki/DEC_alphabet) + 2..9 numbers to decrease ambiguity.
```ruby
Urn.new.value # => "IRPCA2B39"
```
As it implements `.dump` and `.load`, it can be used with `serialize` as
an Active Model. It can be included as an attribute in your model
and automatically handle serialization/deserialization.
Example with ActiveRecord:
```ruby
#app/models/your_model.rb
class YourModel < ActiveRecord::Base
serialize :urn, Urn
end
your_model = YourModel.new
your_model.urn = Urn.new
your_model.save
your_model.reload
puts your_model.urn.value
Urn.dump(Urn.new) # …
```

Add Urn for application numbers

---

app/models/applicant.rb
db/migrate/20230615132013_remove_address_columns_from_applicant.rb
db/schema.rb
spec/factories/applicants.rb

As a follow-up of #62, we need to remove all the address fields from an
`Applicant` as they are now stored on the polymorphic entity: `Address`

Remove old address columns from `Applicant`

---

app/controllers/applicants/employment_details_controller.rb
app/controllers/applicants/personal_details_controller.rb
app/controllers/applicants/submissions_controller.rb
app/controllers/application_controller.rb
app/models/applicant.rb
app/models/applicants/employment_detail.rb
app/models/applicants/personal_detail.rb
app/models/application.rb
app/models/urn.rb
app/views/applicants/submissions/show.html.erb
config/routes.rb
db/migrate/20230619112449_create_applications.rb
db/schema.rb
spec/factories/applications.rb
spec/features/teacher_route_completing_the_form_spec.rb
spec/features/trainee_route_completing_the_form_spec.rb
spec/models/address_spec.rb
spec/models/applicants/employment_detail_spec.rb
spec/models/applicants/personal_detail_spec.rb
spec/models/application_spec.rb
spec/models/school_spec.rb
spec/models/urn_spec.rb
spec/rails_helper.rb
spec/requests/question_for_employment_details_spec.rb
spec/requests/question_for_personal_details_spec.rb

https://trello.com/c/fsy6rp4P/72-teacher-route-exit-page-copy-application-criteria-is-fulfilled
https://trello.com/c/DfypaSU8/71-trainee-exit-page-copy-application-criteria-is-fulfilled
https://trello.com/c/acwINfog/32-m-generate-urn-for-applications-on-submission
Add the exit page for trainee and teachers. Both routes use the same copy for the content. I have used the [GOV.UK guidelines for Applications](https://design-system.service.gov.uk/patterns/confirmation-pages/).
1. Introduces a fix in 89e990e44502b52d211b8d2f3e41a3db93e81398 for #63 because I didn't wrap the value with the `Urn` class to get the most of encapsulation.
2. Introduces a new `request` test for the Personal Details question. This is now needed because I made some changes to how data is persisted.
3. Introduces the …

Add exit pages for Trainees and Teachers

---

app/models/applicants/visa.rb

https://trello.com/c/O4orwiAb/78-teacher-route-add-other-to-visa-option-exit-application-if-selected
Fixes typo with `Afghan citizens resettlement schema` Visa.

Fix typo on Visa name

---

app/controllers/applicants/contract_start_dates_controller.rb
app/controllers/applicants/salaried_course_details_controller.rb
app/views/applicants/submissions/show.html.erb
spec/features/teacher_route_completing_the_form_spec.rb
spec/features/trainee_route_completing_the_form_spec.rb
spec/requests/question_for_contract_start_date_spec.rb
spec/support/application_form_steps.rb

https://trello.com/c/Fl92ae9o/75-trainee-route-start-of-contract-with-the-school
Add Start Date of contract for Trainees
1. We need to add the 3 months validation between the entry date and the start date.

Add start contract question to trainees

---

terraform/aks/application.tf

The AKS application module has had a breaking change made,
and the kv name needs to be updated.
review apps will fail deployment until this change is made.

Fix aks app module kv name after module change

---

app/controllers/applicants/entry_dates_controller.rb
app/models/applicants/entry_date.rb
app/models/policies/entry_date.rb
spec/models/policies/entry_date_spec.rb

https://trello.com/c/Fl92ae9o/75-trainee-route-start-of-contract-with-the-school
https://trello.com/c/Ny4xhpe6/58-trainee-route-users-date-of-entry-into-the-country
Following the work on #79, on this PR I am enabling the eligibility rule that prevents applicants
where the time between the `start_date` and the `entry_date` is above `3 months`.
I have extracted another Policy Object (`Policies::EntryDate`) in the same way I extracted the 
Contract Start Date in #51.

Add entry date validation for trainee

---

app/models/applicants/personal_detail.rb
app/views/applicants/application_routes/new.html.erb
app/views/applicants/contract_details/new.html.erb
app/views/applicants/contract_start_dates/new.html.erb
app/views/applicants/employment_details/new.html.erb
app/views/applicants/personal_details/new.html.erb
app/views/applicants/salaried_course_details/new.html.erb
app/views/applicants/school_details/new.html.erb
app/views/applicants/visas/new.html.erb
config/locales/en.yml

https://trello.com/c/eCID3QEs/92-localize-all-questions-so-they-are-easier-to-maintain
Adds localisation for questions (copy and options) and validation messages for all questions.
The goal is not translation, but to make it easier to maintain through time.

Localise content for questions

---

app/controllers/applicants/personal_details_controller.rb
app/models/applicants/personal_detail.rb
app/models/application.rb
app/models/urn.rb
app/views/applicants/submissions/show.html.erb
spec/factories/applicants.rb
spec/factories/applications.rb
spec/models/applicants/personal_detail_spec.rb
spec/models/application_spec.rb
spec/models/urn_spec.rb
spec/requests/question_for_personal_details_spec.rb

https://trello.com/c/acwINfog/32-m-generate-urn-for-applications-on-submission
Updates the URN so the application number includes the prefix `LT` or `TE` depending
of the type of applicant.
For example, 
```ruby
Urn.generate('teacher')          # => "IRPTE123456"
Urn.generate('salaried_trainee') # => "IRPLT123456"
```

Update Urn algorithm: use only numbers and LT/TE prefix

---

app/models/applicant.rb
app/models/applicant_progress.rb
app/models/application.rb
app/models/application_progress.rb
db/migrate/20230622150827_add_progress_references_to_application.rb
db/migrate/20230622151859_remove_foreign_key_constraint_applicant_to_progress.rb
db/migrate/20230622163508_rename_table_applicant_progress_to_application_progress.rb
db/schema.rb
db/seeds.rb
spec/factories/applicant_progresses.rb
spec/factories/applications.rb

https://trello.com/c/JaErYVUq/131-update-association-from-applicant-to-association-according-to-adr5
According to #73, the `ApplicationProgress` domain model is linked to the `Application` 
and not to the `Applicant`. This makes sense, as there is only progress once the `Application` 
has been created.
On this PR, I take the following steps:
1.  Update FK from `Applicant` to `Application` => `Application` to `ApplicationProgress`
2. Rename the table from `ApplicantProgress` to `ApplicationProgress`
3. Drop old column `applicant_id` on the `application_progress`
Although I am destroying one column, as we have no production data, there is no risk associated with the
database migrations.

Update association after ADR: the progress is linked to an Application

---

app/models/kpis.rb
app/queries/subject_breakdown_query.rb
app/views/system_admin/dashboard/show.html.erb
spec/features/admin_console/dashboard_spec.rb
spec/queries/subject_breakdown_query_spec.rb

Adds a new widget for the subjects breakdown
- Creates a new query object to obtain the subjects breakdown
- Adds a new widget to the dashboard to display the route breakdown
- Adds the necessary tests for the query object and system test for the widget view
https://trello.com/c/nXkigy23

Add a new dashboard widget for the subjects

---

app/models/kpis.rb
app/models/urn.rb
spec/features/admin_console/dashboard_spec.rb
spec/models/application_spec.rb
spec/models/urn_spec.rb

https://trello.com/c/acwINfog/32-m-generate-urn-for-applications-on-submission
Moves back the TE|ST suffix after the `IRP` prefix.
```ruby
#
#
#
#
```

Update URN format to correct specs

---

app/models/applicant.rb

This code is not in used. Indeed, it can't be used, because there is no 
association between applicant and progress since we updated the domain in #89

Remove unused delegation in Applicant

---

.github/workflows/build-and-deploy.yml
Gemfile
Gemfile.lock
config/initializers/okcomputer.rb
spec/requests/healthchecks_spec.rb

Supersedes #83
Following [suggestion](https://github.com/DFE-Digital/get-a-teacher-relocation-payment/pull/83#pullrequestreview-1498160709) by @thomasleese, provides healchecks via [okcomputer gem](https://github.com/sportngin/okcomputer). 
The current configuration enables the following endpoints:
1. /healthcheck/default
_This Healthcheck only validates that the applications is `up` regardless of the database._
```
default: PASSED Application is running (0.000s)
```
2. /healcheck/database
```
database: PASSED Schema version: 20230628135130 (0.003s)
```
3. /healthcheck/version
```
version: PASSED Version: 10dd57d99596dcc0518a9269899aaa6413f30a6a (0.000s) (OPTIONAL)
```
4. /healthcheck/all
```
Default Collection
database: PASSED Schema version: 20230628135130 (0.003s)
default: PASSED …
```

Use Okcomputer gem for Healthchecks

---

Gemfile
db/seeds.rb

We need to move the factory_bot_rails gem out of development group so it can
be installed when in production environments and the database seeding works.

Move FactoryBot out of the development group

---

app/controllers/applicants/employment_details_controller.rb
app/controllers/applicants/personal_details_controller.rb
app/models/address.rb
app/models/applicants/employment_detail.rb
app/models/applicants/personal_detail.rb
app/views/applicants/employment_details/new.html.erb
app/views/applicants/personal_details/new.html.erb
config/locales/en.yml
db/migrate/20230705133229_remove_county_from_address.rb
db/schema.rb
spec/factories/addresses.rb
spec/models/address_spec.rb
spec/models/applicants/employment_detail_spec.rb
spec/models/applicants/personal_detail_spec.rb
spec/requests/question_for_employment_details_spec.rb
spec/requests/question_for_personal_details_spec.rb
spec/support/application_form_steps.rb

https://trello.com/c/iLM73Wos/140-edits-to-the-employment-page-reviewed-by-laura
https://trello.com/c/IaH6ZW93/139-edits-to-personal-information-page-reviewed-by-laura
Removes `County` from the applicant journey (entering address); as per User Research
findings this seems to be confusing for our users.
It also perform minor updates the content copy for the personal info page.

Remove county from Address (address User Research)

---

README.md
public/robots.txt

https://trello.com/c/hc45OQs6/145-disallow-web-crawlers-and-robots-to-crawl-the-site
Updates the robots.txt file to disallow access to all directories and
files ("/") for all web crawlers ("User-agent: *"). This ensures that all web
crawlers are prevented from crawling and indexing any pages on the website,
effectively blocking it from search engine results.
```txt
User-agent: *
Disallow: /
```

Disable all web crawlers for pen-testing

---

app/controllers/system_admin/reports_controller.rb
app/models/reports/payroll.rb
app/views/system_admin/reports/index.html.erb
spec/features/admin_console/reports_spec.rb
spec/models/reports/payroll_spec.rb

https://trello.com/c/NMAhMvxu/128-service-settings-download-csv-for-payroll
Following work on #144. and #145 , we are including a new report: `Payroll Report`, which 
returns the following fields:
```ruby
%w[
URN
Forename
Surname
DOB
Gender
Email
Address
Postcode
Telephone
]
```
It will list only applicants with baking details approved.

Export CSV: payroll

---

app/models/reports/home_office.rb
spec/models/reports/home_office_spec.rb

https://trello.com/c/ZHLorhH6/126-service-settings-download-csv-for-ho
Do not include Rejected applicants in Home Office report.

Remove rejected applicants from HomeOffice report

---

app/views/pages/closed.html.erb

- https://trello.com/c/aEqooIHr/129-service-settings-add-a-toggle-to-open-close-applications-service
- https://trello.com/c/KBaRff09/89-application-window-closed-page
We have decided to remove the start date from the application close page.

Remove start service date from service closed page

---

db/migrate/20230816100957_update_duplicate_applications_to_version_2.rb
db/schema.rb
db/views/duplicate_applications_v02.sql
spec/features/admin_console/duplicates_search_spec.rb

There was an error where the applications that are "in progress" or "abandoned", will be included on the
duplicates table, but since the wont have yet all the required data, like an `application_progress` relationship,
it will return errors when trying to display them on the Duplicates view.
This updates the database view query to only include applications that have a URN therefore have already being submitted.

Fix duplicates error

---

config/initializers/nationalities.rb
spec/support/application_form_steps.rb

-------
`English`, `Scottish` and `Welsh` are removed from the nationalities list
[Remove Nationalites](https://trello.com/c/KQ2ojIx3/182-sremove-english-welsh-and-scottish-from-nationalities-drop-down)
https://trello.com/c/

Remove nationalities

---

app/models/applicant.rb
app/models/form.rb
app/models/form/completeness_check.rb
app/services/submit_form.rb
app/steps/base_step/answer.rb
app/steps/personal_details_step.rb
app/views/step/personal_details.html.erb
app/views/system_admin/applicants/show.html.erb
db/migrate/20230825102934_add_student_loan_columns.rb
db/schema.rb
spec/factories/applicants.rb
spec/factories/forms.rb
spec/models/form/completeness_check_spec.rb
spec/models/form_spec.rb
spec/models/summary_spec.rb
spec/steps/personal_details_step_spec.rb
spec/support/application_form_steps.rb

-------
Add student_loan question to personal details page
save value in form and upon submissions adds it to the applicant.student_loan field
[StudentLoan](https://trello.com/c/Ige3Yr3T/180-sadd-in-question-about-student-loan-to-personal-details-page-as-a-preference-or-on-additional-button-page-if-needed)

Add `Student Loan` question in personal details step

---

app/helpers/application_helper.rb

-------
Fix MS Form link to the feedback banner
https://trello.com/c/cgDx9fV1/175-sbuild-feedback-form-behind-the-private-beta

Fix MS Form link to the feedback banner

---

app/models/applicants/personal_detail.rb
app/steps/personal_details_step.rb
spec/models/applicants/personal_detail_spec.rb
spec/steps/personal_details_step_spec.rb

Adding passport validation
https://trello.com/c/31ixtiBX

Adding passport validation

---

app/controllers/system_admin/audits_controller.rb
app/models/application_progress.rb

There was an error when creating audits for the application progress when a new application was created.
This fix limits the auditing to only when the 'application_progress' model is updated.
Also the controller will fetch audits that have a user_id.
https://trello.com/c/LrzvNeQn

Fix audit errors

---

terraform/aks/config/production.tfvars.json
terraform/aks/config/qa.tfvars.json
terraform/aks/config/staging.tfvars.json
terraform/aks/monitoring.tf
terraform/aks/terraform.tf
terraform/aks/variables.tf

Add statuscake monitoring for each env
test with
make qa|staging|production terraform-plan
https://trello.com/c/NQnuLXUr/536-irp-statuscake-monitoring

Add statuscake monitoring

---

Gemfile
Gemfile.lock
terraform/aks/config/production.tfvars.json
terraform/aks/config/qa.tfvars.json
terraform/aks/config/review.tfvars.json
terraform/aks/config/staging.tfvars.json

* Prod and Staging redis version is not supported by the latest version of sidekiq. Review environment uses docker for redis which picks up the latest version and allowed sidekiq version 7
* udpate startup_command to match Dockerfile

Downgrade sidekiq version

---

.rubocop.yml
app/models/reports/home_office.rb
spec/models/reports/home_office_spec.rb

Header:   "ID", application.urn
"Full Name", application.full_name
"DOB", applicant.date_of_birth
"Gender",
"Nationality", applicant.nationality
"Place of Birth",
"Passport Number", applicant.passport_number
"Address",
"Postcode",
"Email",
"Telephone",
"Reference",
https://trello.com/c/etFQUL8H/202-ho-csv

Updated HO csv

---

app/controllers/application_controller.rb
app/controllers/system_admin/applicants_controller.rb
app/models/application.rb
app/models/kpis.rb
app/queries/average_age_query.rb
app/queries/gender_breakdown_query.rb
app/queries/nationality_breakdown_query.rb
app/queries/rejection_reason_breakdown_query.rb
app/queries/route_breakdown_query.rb
app/queries/subject_breakdown_query.rb
app/queries/visa_breakdown_query.rb
app/services/submit_form.rb
spec/factories/applications.rb
spec/features/admin_console/applications_list_spec.rb
spec/features/admin_console/download_qa_csv_file_spec.rb
spec/features/admin_console/duplicates_search_spec.rb
spec/models/application_spec.rb
spec/models/kpis_spec.rb
spec/queries/average_age_query_spec.rb
spec/queries/gender_breakdown_query_spec.rb
spec/queries/nationality_breakdown_query_spec.rb
spec/queries/rejection_reason_breakdown_query_spec.rb
spec/queries/route_breakdown_query_spec.rb
spec/queries/subject_breakdown_query_spec.rb
spec/queries/visa_breakdown_query_spec.rb

Remove concept of submitted application
The SubmitForm service creates submitted application and we no longer
have unsubmitted applications to consider in the system-admin code.
The Forms are now what used to be unsubmitted applications.
Original PR #259 was reverted in #263  because of production issues caused by bogus test data created prior official launch date that have now been removed.
https://trello.com/c/hr5LvhT7/205-code-cleanup

Code cleanup

---

app/steps/personal_details_step.rb
config/locales/steps.en.yml
spec/steps/personal_details_step_spec.rb

Change applicant minimum age from 22 to 21
https://trello.com/c/hx7IeaJA/210-update-applicant-minimum-age-to-21

Change applicant minimum age from 22 to 21

---

app/models/kpis.rb
app/queries/status_breakdown_query.rb
app/views/system_admin/dashboard/show.html.erb
spec/queries/status_breakdown_query_spec.rb

Add Kpi status breakdown
https://trello.com/c/hPT1pL2Y/209-add-new-kpi-widget-with-a-breakdown-of-the-each-status

Add Kpi status breakdown

---

app/models/urn.rb
app/services/generate_urns.rb
app/services/submit_form.rb
bin/app-startup.sh
db/migrate/20230927092305_create_urns.rb
db/schema.rb
lib/tasks/urn.rake
spec/factories/applications.rb
spec/factories/urns.rb
spec/features/admin_console/applications_list_spec.rb
spec/fixtures/urns.yml
spec/models/urn_spec.rb
spec/rails_helper.rb
spec/services/generate_urns_spec.rb
spec/services/submit_form_spec.rb

Pre generate all URNs

---

app/models/form/eligibility_check.rb
app/queries/forms_funnel_query.rb

-------
some user fill in the date-of-entry step before the start-date
and this caused a bug in the form analytic widget which assumed that
the form was filled in the order expected.
TODO: This type of behaviour could be used as a way to flag potential
fraudulent applications.

When applicant do not follow the form natural step order

---

config/locales/steps.en.yml
spec/steps/subject_step_spec.rb

Please can you remove: This will be validated by Department for Education with the school where you are training.
This is so that it matches the teacher route.
https://trello.com/c/5gpDi3ow/226-please-edit-subject-question-in-salaried-trainee-route

Copy changes for salaried_trainee subject step

---

app/validators/application_progress_validator.rb
spec/validators/application_progress_validator_spec.rb

Fix upper check in application progress date validation

Fix upper check in application progress date validation

---

app/controllers/system_admin/applicants_controller.rb
app/controllers/system_admin/reports_controller.rb
app/views/layouts/admin.html.erb
app/views/system_admin/reports/index.html.erb
config/initializers/flipper.rb
config/locales/en.yml
db/seeds.rb
spec/features/admin_console/applications_list_spec.rb
spec/features/admin_console/dashboard_spec.rb
spec/features/admin_console/duplicates_search_spec.rb
spec/features/admin_console/reports_spec.rb
spec/features/admin_console/settings_spec.rb
spec/features/admin_console/update_progress_spec.rb
spec/features/admin_console/users_spec.rb
spec/features/open_close_spec.rb
spec/support/admin_helpers.rb

User Role Restricitons
https://trello.com/c/kBLYVcwH

User Role Restrictions

---

Gemfile

Currently the Azure only offer redis version 6.x
However from sidekiq version 7.x, support for redis 6.x has been
dropped.
This issue affected the Azure platform and not the Review environment
which uses docker, which provides the latest version of redis.

Add warning on sidekiq gem

---

.rubocop.yml
app/assets/stylesheets/custom.scss
app/controllers/system_admin/reports_controller.rb
app/helpers/audit_message_helper.rb
app/models/reports/base.rb
app/models/reports/home_office_csv.rb
app/models/reports/home_office_excel.rb
app/models/reports/payroll.rb
app/models/reports/qa_report.rb
app/models/reports/standing_data.rb
app/services/report.rb
app/views/system_admin/audits/_app_settings.html.erb
app/views/system_admin/audits/_application_progress.html.erb
app/views/system_admin/audits/_changed_summary.html.erb
app/views/system_admin/audits/_report.html.erb
app/views/system_admin/audits/_user.html.erb
app/views/system_admin/audits/index.html.erb
config/routes.rb
spec/factories/roles.rb
spec/helpers/audit_message_helper_spec.rb
spec/models/reports/home_office_excel_spec.rb
spec/models/reports/payroll_spec.rb
spec/models/reports/qa_report_spec.rb
spec/models/reports/standing_data_spec.rb
spec/rails_helper.rb
spec/services/report_spec.rb

In order to render the ops teams self sufficient add the ability to reset a specific report when a error has occured. (ie file lost) 
Condition:
When feature `Flipper.enabled?(:reset_reports)` 
and the current user has the role admin 
and the report has not been already resetted
Then display a reset report button
Screenshots
Before:
After:
After reset report:

Add report reset button

---

README.md
app/models/form/eligibility_check.rb
config/application.rb
config/locales/en.yml
spec/factories/forms.rb
spec/models/form/eligibility_check_spec.rb
spec/support/time_helpers.rb

Upgrade the code for the eligibility check on the form for the contract start date, so that it works as expected in 2024.
Added the option to configure a 5 month window for the date as an alternative to the default of 6.  The custom rails configuration entry `config.x.form_eligibility.contract_start_months_limit` can be set to `5` to allow this.  If the entry is set to anything other than 5 or 6 it will default to 6 months.
[Fix for contract start date](https://trello.com/c/hv4fBjnR/265-bug-fix-on-current-dates-in-application-form)

Update contract start date rules (#265)

---

app/views/pages/index.html.erb

- Remove the text `later in 2024` from the `express interest...` link content 
- Add the comma back after `funded by the UK government`
https://trello.com/c/7HIMxjYX/267-implement-new-landing-page-content

Landing Page minor change

---

.github/actions/deploy/action.yml
.github/workflows/database-backup.yml
.github/workflows/delete-review-app.yml
Makefile
docs/aks-cheatsheet.md
terraform/aks/terraform.tf

Enable azure rbac on deployment (for when it is enabled in the cluster)
https://trello.com/c/3m8PNLG6/937-enable-azure-rbac-deployment-on-all-services
Not to be deployed until terraform modules has been updated on Monday Jan 29th.
Update Makefile, terraform and workflows to use rbac if configured for the cluster
make env terraform-plan
check review app deploys successfully

Enable azure rbac deployment

---

.github/workflows/database-backup.yml

Add set-kubelogin to database backup workflow, as this is required after adding rbac authentication
Run manually against branch. see https://github.com/DFE-Digital/get-a-teacher-relocation-payment/actions/runs/7724602277

Add set-kubelogin to database backup workflow

---

terraform/aks/config/production.tfvars.json

The Teacher payments team are now responsible for the service. Add their group to statuscake alerting.
https://trello.com/c/Z6eliKhq

[1654] Add Teacher payments contact group

---

app/views/pages/ineligible_salaried_course.html.erb
app/views/pages/shared/_body.html.erb
spec/features/trainee_route_completing_the_form_spec.rb

Removes the additionaly copy from the ineligible_salaried_course page
https://github.com/DFE-Digital/get-a-teacher-relocation-payment/assets/9936028/b8b68546-a6d0-49f8-b327-7e36e8ca0bb4
https://dfedigital.atlassian.net/browse/CAPT-1629

Remove additionaly copy from the ineligible_salaried_course page

---

Gemfile
Gemfile.lock
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/semantic_logger.rb

Configures the app to format it's logs with `rails_semantic_logger` so
logit can ingest them.
https://technical-guidance.education.gov.uk/infrastructure/monitoring/logit/#ruby-on-rails
Assumes app is logging to standard out in production
Also bumps some gems for security audit

Configure semantic logger

---

.github/actions/deploy/action.yml
terraform/aks/terraform.tf
terraform/custom_domains/environment_domains/terraform.tf
terraform/custom_domains/infrastructure/terraform.tf

https://trello.com/c/ST9hu2Bq/1840-update-azurerm-provider-to-31042
Update terraform providers as azurerm is using a version of the preview api that will become eol
Also update github actions in the deploy action to latest versions
azurerm 3.43.0/3.53.0 -> 3.104.2
statuscake 2.1.0 -> 2.2.0
kubernetes 2.20.0 -> 2.30.0
make env terraform-plan
make dns domains-infra-plan
make qa dns domains-plan
redis will show below. data_persistence_authentication_method was added in a later module, SAS is the default.
```
~ resource "azurerm_redis_cache" "main" {
~ redis_configuration {
+ data_persistence_authentication_method  = "SAS"
}
```

Update azurerm provider

---

terraform/custom_domains/environment_domains/config/trp_production.tfvars.json
terraform/custom_domains/environment_domains/main.tf

[get-a-teacher-relocation-payment.education.gov.uk](http://get-a-teacher-relocation-payment.education.gov.uk/) needs to be decommission, but before that happens we want to redirect the old service url to another url.
Set up a redirect from domain get-a-teacher-relocation-payment.education.gov.uk for both http and https and if there is any path on the end ignore it and just redirect to https://getintoteaching.education.gov.uk/non-uk-teachers/get-an-international-relocation-payment
https://trello.com/c/zu452h7b/2046-setup-redirect-from-get-a-teacher-relocation-payment-to-https-getintoteachingeducationgovuk-non-uk-teachers-get-an-international
https://trello.com/c/

2046-setup-redirect-from-get-a-teacher-relocation-payment

---

terraform/custom_domains/environment_domains/config/trp_production.tfvars.json
terraform/custom_domains/environment_domains/main.tf

The service is still needed and the redirect must be reverted, at least temporarily
https://trello.com/c/zu452h7b

[2046] Revert redirect

---

app/controllers/application_controller.rb
spec/features/admin_console/settings_spec.rb
spec/features/open_close_spec.rb

- https://dfedigital.atlassian.net/browse/CAPT-1819
- Hard redirect closed service to offsite guidance page
- Theres failing test I can't figure out, I wanted to pend but linter complains, so it has been deleted

Hard redirect offsite
